'use strict';

import * as _ from 'lodash';
import { Singleton, AutoWired, Inject } from 'typescript-ioc';
import { Database } from '../database';
import { ConfigPackageService } from '../service/config-package';
import chalk from 'chalk';
import { GatewayConfig } from '../config/gateway';
import { ApiConfig } from '../config/api';
const compareVersions = require('compare-versions');

@Singleton
@AutoWired
export class VersionUpgrades {
    @Inject private database: Database;
    @Inject private service: ConfigPackageService;

    checkGatewayVersion(): Promise<void> {
        return new Promise<void>((resolve, reject) => {
            const packageJson = require('../../package.json');
            this.database.getGatewayVersion()
                .then(version => {
                    const compared = compareVersions(packageJson.version, version || '0.0.1');
                    if ( compared === 0) {
                        return resolve();
                    } else if (compared < 0) {
                        return reject(new Error('Can not load configuration. This configuration repository contains information generated by a newer tree-gateway version. Try to update tree-gateway, running npm i -g tree-gateway.'));
                    }
                    this.updateGatewayConfiguration()
                        .then(resolve)
                        .catch(reject);
                })
                .catch(reject);
        });
    }

    private updateGatewayConfiguration() {
        return new Promise<void>((resolve, reject) => {
            this.database.startGatewayUpdate()
            .then((previous: string) => {
                if (previous !== Database.UPDATING) {
                    return this.update(previous);
                } else {
                    return this.wait(0);
                }
            })
            .then(resolve)
            .catch(reject);
        });
    }

    private update(version: string) {
        return new Promise<void>((resolve, reject) => {
            if (compareVersions(version || '0.0.1', '3.0.0') < 0) {
                this.service.get()
                    .then(pac => {
                        if (pac && pac.gateway) {
                            console.info(chalk.magenta('An older configuration was found. Updating it to the newer format. '
                                                            + 'Check tree-gateway migration guide for more info.'));
                            pac.gateway = <GatewayConfig>_.omit(pac.gateway, 'statsConfig', 'monitor');
                        }
                        if (pac.apis) {
                            pac.apis = pac.apis.map(api => {
                                if (_.has(api, 'proxy.disableStats')) {
                                    api.disableStats = _.get(api.proxy, 'disableStats');
                                }
                                return <ApiConfig>_.omit(api, 'proxy.statsConfig', 'proxy.disableStats');
                            });
                        }
                        return this.service.set(pac);
                    })
                    .then(() => this.database.registerGatewayVersion())
                    .then(resolve)
                    .catch(reject);
            } else {
                resolve();
            }
        });
    }

    private wait(count: number) {
        return new Promise<void>((resolve, reject) => {
            if (count > 10) {
                return reject(new Error('Can not upgrade gateway configuration.'));
            }
            setTimeout(() => {
                this.database.getGatewayVersion()
                    .then(version => {
                        if (version === Database.UPDATING) {
                            this.wait(count++)
                                .then(resolve)
                                .catch(reject);
                        } else {
                            resolve();
                        }
                    });
            }, 100);
        });
    }
}
